name: Unit Tests

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        host-os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
      fail-fast: false

    runs-on: ${{ matrix.host-os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          set -vxeuo pipefail
          cd python
          python setup.py install

      - name: Install test requirements
        run: |
          set -vxeuo pipefail
          cd python
          python -m pip install -r requirements-dev.txt
          python -m pip list

      - name: Test with pytest
        run: |
          set -vxeuo pipefail
          cp -rv python/srwpy/tests tests
          pytest -s -vv tests/
